In [17]:
import pandas as pd
import numpy as np

In [65]:
df=pd.read_csv(r"C:\Users\mayak\OneDrive\Desktop\fastapi\cleaned_house_data.csv")

In [66]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [67]:
df.shape

(13320, 9)

In [68]:
df.select_dtypes(include='str').columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft'],
      dtype='str')

In [69]:
df.select_dtypes(include=np.number).columns

Index(['bath', 'balcony', 'price'], dtype='str')

In [70]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [71]:
df.isna().sum()/len(df)*100

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [72]:
df=df.drop('society',axis=1)

In [73]:
df.shape

(13320, 8)

In [74]:
df['location']=df['location'].fillna(df['location'].mode()[0])
df['size']=df['size'].fillna(df['size'].mode()[0])

In [75]:
Q1=df['bath'].quantile(0.25)
Q3=df['bath'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=df[(df['bath']<lower)|(df['bath']>upper)]
print('25% range:',lower)
print('75% range:',upper)
print('outlier range :',len(outliers))

25% range: 0.5
75% range: 4.5
outlier range : 1039

In [76]:
df['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
14.0       1
27.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

In [77]:
Q1=df['balcony'].quantile(0.25)
Q3=df['balcony'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=df[(df['balcony']<lower)|(df['balcony']>upper)]
print('25% range:',lower)
print('75% range:',upper)
print('outlier range :',len(outliers))

25% range: -0.5
75% range: 3.5
outlier range : 0

In [78]:
df['balcony'].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [79]:
df['bath']=df['bath'].fillna(df['bath'].median())
df['balcony']=df['balcony'].fillna(df['balcony'].median())

In [80]:
df.duplicated().sum()

np.int64(569)

In [81]:
df=df.drop_duplicates()

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
df['location'] = df['location'].str.strip()
df['size'] = df['size'].str.strip()

In [85]:
df['BHK'] = df['size'].str.extract(r'(\d+)').astype(float)

In [86]:
df[['size', 'BHK']].head(10)

        size  BHK
0      2 BHK  2.0
1  4 Bedroom  4.0
2      3 BHK  3.0
3      3 BHK  3.0
4      2 BHK  2.0
5      2 BHK  2.0
6      4 BHK  4.0
7      4 BHK  4.0
8      3 BHK  3.0
9  6 Bedroom  6.0

In [87]:
def convert_sqft_to_num(x):
    try:
        if '-' in str(x):
            tokens = str(x).split('-')
            return (float(tokens[0]) + float(tokens[1])) / 2
        
        return float(x)
    
    except:
        return np.nan

In [89]:
df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

In [90]:
df['total_sqft'].head(10)

0    1056.0
1    2600.0
2    1440.0
3    1521.0
4    1200.0
5    1170.0
6    2732.0
7    3300.0
8    1310.0
9    1020.0
Name: total_sqft, dtype: float64

In [91]:
df['total_sqft'].isnull().sum()

np.int64(46)

In [92]:
df = df.dropna(subset=['total_sqft'])

In [93]:
df['total_sqft'].isnull().sum()

np.int64(0)

In [94]:
print("BHK <= 0:", (df['BHK'] <= 0).sum())
print("total_sqft <= 0:", (df['total_sqft'] <= 0).sum())
print("bath <= 0:", (df['bath'] <= 0).sum())

BHK <= 0: 0
total_sqft <= 0: 0
bath <= 0: 0

In [95]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
BHK             0
dtype: int64

In [99]:
df.duplicated().sum()

np.int64(1)

In [101]:
df[df.duplicated()]

,area_type,availability,location,size,total_sqft,bath,balcony,price,BHK
8268,Super built-up Area,Ready To Move,Devarachikkanahalli,2 BHK,1230.0,2.0,1.0,58.0,2.0

In [102]:
df=df.drop_duplicates()

In [103]:
df.duplicated().sum()

np.int64(0)

In [105]:
df.to_csv("cleaned_house_data.csv", index=False)